version: "3.8"
services: 
    webapp:
        build: .
        ports: 
            - "8080:8080"
        volumes:
            - ./build/libs:/home/app
        links:
            - db
        environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/barcamp?autoReconnect=true&useSSL=false
    db:
        container_name: mysql-db
        image: mysql:5.7.26
        ports:
            - "33006:3306"
        volumes:  
            - type: volume
              source: data
              target: /var/lib/mysql
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=123456 
            - MYSQL_DATABASE=barcamp

volumes:
    data:
